#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9


# /usr/bin/chwal.sh &

# wal -i ~/Pictures/walls/ &

wal -R &

sleep 3

$HOME/.config/polybar/launch.sh &

sleep 1

. "${HOME}/.cache/wal/colors.sh"

# maybe make it so that instead of sourcing why not just put the color hext code inside here

# Set the border colors.
bspc config normal_border_color "$background"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color1"
bspc config border_width         4
bspc config window_gap           10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true



